--UC-1
create database PayRoll_Service
use PayRoll_Service

--UC-2
CREATE TABLE Employee_Payroll(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(20) NOT NULL,
SALARY FLOAT NOT NUll,
START_DATE DATE NOT NULL
)

--UC-3
INSERT INTO Employee_Payroll VALUES('Harini',15000,'2022-06-19')
INSERT INTO Employee_Payroll VALUES('Harshini',25000,'2022-06-01')
INSERT INTO Employee_Payroll VALUES('Pardhavi',20000,'2018-02-25')
INSERT INTO Employee_Payroll VALUES('SENTHIL',25000,'2021-01-01')
INSERT INTO Employee_Payroll VALUES('PRIYA',10000,'2018-01-01')
INSERT INTO Employee_Payroll VALUES('RAMYA',40000,'2019-01-01')
INSERT INTO Employee_Payroll VALUES('LALITHA',30000,'2020-01-01')

--UC-4
SELECT * FROM Employee_Payroll

--UC-5
SELECT NAME,SALARY FROM Employee_Payroll WHERE NAME='Harini'
SELECT * FROM Employee_Payroll WHERE START_DATE BETWEEN '2021-06-01' AND CURRENT_TIMESTAMP

--UC-6
--ALTER TABLE employ_PayRoll ADD gender CHAR(10) CHECK (Gender IN ('M','F'));
ALTER TABLE Employee_Payroll ADD GENDER VARCHAR(10) NULL
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Senthil'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'RAMYA'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'LALITHA'

--UC7:
SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM EMPLOYEE_PAYROLL GROUP BY GENDER

--UC8:
ALTER TABLE EMPLOYEE_PAYROLL ADD MOBILE DECIMAL NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 123 WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 456 WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 789 WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 1011 WHERE NAME = 'LALITHA'
ALTER TABLE EMPLOYEE_PAYROLL ADD ADDRESS VARCHAR(100) NOT NULL DEFAULT(''), DEPARTMENT VARCHAR(50) NOT NULL DEFAULT('')
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'A',DEPARTMENT = 'Production' WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'B',DEPARTMENT = 'Administration' WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'C',DEPARTMENT = 'IT_Support' WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'D',DEPARTMENT = 'Production' WHERE NAME = 'LALITHA'

--UC9:
ALTER TABLE EMPLOYEE_PAYROLL ADD BASIC_PAY FLOAT NOT NULL DEFAULT(0), DEDUCTIONS FLOAT NOT NULL DEFAULT(0),
TAXABLE_PAY FLOAT NOT NULL DEFAULT(0), NET_PAY FLOAT NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 1
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 2
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 15000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 14600 WHERE ID = 3
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 20000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 19600 WHERE ID = 4

--UC10:
INSERT INTO EMPLOYEE_PAYROLL VALUES('Terisa',15000,'2021-01-01','F',9876543210,'Chennai','Sales&Marketing',15000,200,200,14600)
UPDATE EMPLOYEE_PAYROLL SET NAME = 'Harshini' WHERE ID = 5

Select * from Employee_Payroll

